version: '3.4'

services:
  sql.data:
    image: "microsoft/mssql-server-linux:2017-GA"
    environment:
        SA_PASSWORD: "bV4URbLQrSHe8ww7"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    network_mode: "bridge"
